# Compose file for Prometheus and Grafana

version: '2'

services:
  promserver:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-volume:/prometheus
    # - $PWD/alert.rules:/etc/prometheus/alert.rules
    ports:
      - "8088:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-volume:/var/lib/grafana
      - grafana-volume:/etc/grafana
    ports:
      - 8086:3000

volumes:
  grafana-volume:
  prometheus-volume:
